branches:
  only:
    - master
    - gh-pages

language: node_js

node_js:
  - "0.8.11"

before_install:
  - npm install -g grunt-cli recess bower
  - bower install bootstrap#2.3.2

script: "grunt swatch"